name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        # with:
        #   build:  npx cypress run --spec  cypress/e2e/telnyx/specs/*.cy.js
